# Generated by Django 3.0.3 on 2021-01-05 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('tel', models.IntegerField()),
                ('quat', models.CharField(max_length=100)),
                ('datenaiss', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Intendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=140)),
                ('prenom', models.CharField(max_length=100)),
                ('tel', models.IntegerField()),
                ('quat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('tel', models.IntegerField()),
                ('quat', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ins', models.DateTimeField(auto_now_add=True)),
                ('validation', models.BooleanField(default=False)),
                ('annee_academique', models.CharField(default='2021-2022', max_length=100)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Eleve')),
                ('intendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Intendant')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.profile')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Serie'),
        ),
    ]
